# Generated by Django 4.2.2 on 2023-06-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overrated', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='public_key',
            field=models.TextField(default='0x17C360CBfa39E218fB49CA754eC53af31684DD05'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='myuser',
            constraint=models.CheckConstraint(check=models.Q(('public_key__length__gte', 42), ('public_key__length__lte', 42)), name='public_key_length'),
        ),
    ]
